<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.fpm.di.exceptionalBehaviour.ExceptionalExample" tests="3" skipped="0" failures="0" errors="0" timestamp="2021-11-25T08:19:42" hostname="rinkuro" time="0.005">
  <properties/>
  <testcase name="sholdThrowError1" classname="org.fpm.di.exceptionalBehaviour.ExceptionalExample" time="0.001"/>
  <testcase name="shouldThrowError2" classname="org.fpm.di.exceptionalBehaviour.ExceptionalExample" time="0.001"/>
  <testcase name="shouldThrowError3" classname="org.fpm.di.exceptionalBehaviour.ExceptionalExample" time="0.001"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
